version: '3.8'

services:
  home_chat:
    build:
      context: .
      target: production
    ports:
      - '3031:3031'
    environment:
      - NODE_ENV=production
    volumes:
      - chat-db:/app/db
      - /etc/home_chat/certs:/app/certs
volumes:
  chat-db:
